library(ggplot2)
library(stringr)
library(dplyr)
library(patchwork)
library(tidyr)

setwd('/home/chey120/chainA_chainA/preMD_analysis')
list_4x52=list.files(pattern="*_4x5w.sc")
list_5ni9=list.files(pattern="*_5ni9.sc")
list_4x52_rev=list.files(pattern="*4x5w_rev.sc")
list_5ni9_rev=list.files(pattern="*5ni9_rev.sc")
list_recom=list.files(pattern="*2.sc")

#read-in
for (i in 1:length(list_4x52)){
  temp = read.table(list_4x52[i], header=TRUE)
  name = str_replace(list_4x52[i], "rmsd_trim_", "")
  name = str_replace(name, ".sc", "")
  temp <- temp %>% 
    mutate(sequence = name) %>%
    mutate(type = '4x5w')
  if (i==1) {
    data_4x5w <- temp
  }else{
    data_4x5w <- bind_rows(data_4x5w, temp)
  }
}

for (i in 1:length(list_5ni9)){
  temp = read.table(list_5ni9[i], header=TRUE)
  name = str_replace(list_5ni9[i], "rmsd_trim_", "")
  name = str_replace(name, ".sc", "")
  temp <- temp %>% 
    mutate(sequence = name) %>%
    mutate(type = '5ni9')
  if (i==1) {
    data_5ni9 <- temp
  }else{
    data_5ni9 <- bind_rows(data_5ni9, temp)
  }
}

for (i in 1:length(list_4x52_rev)){
  temp = read.table(list_4x52_rev[i], header=TRUE)
  name = str_replace(list_4x52_rev[i], "rmsd_", "")
  name = str_replace(name, ".sc", "")
  temp <- temp %>% 
    mutate(sequence = name) %>%
    mutate(type = '4x5w_rev')
  if (i==1) {
    data_4x5w_rev <- temp
  }else{
    data_4x5w_rev <- bind_rows(data_4x5w_rev, temp)
  }
}

for (i in 1:length(list_5ni9_rev)){
  temp = read.table(list_5ni9_rev[i], header=TRUE)
  name = str_replace(list_5ni9_rev[i], "rmsd_", "")
  name = str_replace(name, ".sc", "")
  temp <- temp %>% 
    mutate(sequence = name) %>%
    mutate(type = '5ni9_rev')
  if (i==1) {
    data_5ni9_rev <- temp
  }else{
    data_5ni9_rev <- bind_rows(data_5ni9_rev, temp)
  }
}

for (i in 1:length(list_recom)){
  temp = read.table(list_recom[i], header=TRUE)
  name = str_replace(list_recom[i], "rmsd_", "")
  name = str_replace(name, "trim_", "")
  name = str_replace(name, ".sc", "")
  temp <- temp %>% 
    mutate(sequence = name) %>%
    mutate(type = 'recom')
  if (i==1) {
    data_recom <- temp
  }else{
    data_recom <- bind_rows(data_recom, temp)
  }
}

data_4x5w <- bind_rows(data_4x5w, data_4x5w_rev)
data_5ni9 <- bind_rows(data_5ni9, data_5ni9_rev)
total <- bind_rows(data_5ni9, data_4x5w)
total <- bind_rows(total, data_recom)

#data processing
total <- total %>%
  distinct(description,.keep_all = TRUE) %>%
  rowwise() %>% 
  mutate(h_sum_res_summary=sum(c_across(starts_with("hbonds_")), na.rm = T))

rmsd <- total %>%
  filter(rmsdvs_lowest < 0.5)
count <- count(rmsd, sequence)
rmsd <- rmsd %>%
  left_join(count, by = "sequence")
min <- total %>%
  group_by(sequence) %>%
  filter(total_score == min(total_score)) 
type <- total %>%
  select(sequence, type)

sum <- total %>%
  group_by(sequence) %>%
  summarise_if(is.numeric, mean, na.rm = TRUE) %>%
  left_join(type, by="sequence") %>%
  distinct(sequence,.keep_all = TRUE)
sum_hbond <- sum %>%
  select(c(type, hbonds_180,hbonds_181,hbonds_182,hbonds_183,hbonds_184,hbonds_185,hbonds_186,hbonds_187,hbonds_188,hbonds_189,hbonds_190,hbonds_191,hbonds_192,hbonds_193,hbonds_194)) %>%
  group_by(type) %>%
  summarise_if(is.numeric, mean, na.rm = TRUE) 
sum_hbond <-pivot_longer(sum_hbond, !type)
sum_rmsd <- rmsd %>%
  group_by(sequence) %>%
  summarise_if(is.numeric, mean, na.rm = TRUE) %>%
  left_join(type, by="sequence")%>%
  distinct(sequence,.keep_all = TRUE)
native <- sum %>%
  filter(sequence == 'CLIP_WT_5ni9' | sequence == 'CLIP_M107W_5ni9' | sequence == 'CLIP_WT_4x5w' | sequence == 'CLIP_M107W_4x5w') 

#plotting
sum_hbond %>%
  filter(type=="4x5w_rev"| type== "5ni9_rev") %>%
  ggplot(aes(x=name, y=value, fill=type)) +
  geom_bar(stat="identity", position = "dodge")  +   
  theme(axis.text.x=element_text (angle =45, hjust =1, size = 7), legend.position = 'top') +
  labs(title ="individual_hbonds -> reverse direction") +
  scale_fill_brewer(palette = "Pastel2")

sum_hbond %>%
  filter(type=="4x5w"| type== "5ni9") %>%
  ggplot(aes(x=name, y=value, fill=type)) +
  geom_bar(stat="identity", position = "dodge")  +   
  theme(axis.text.x=element_text (angle =45, hjust =1, size = 7), legend.position = 'top') +
  labs(title ="individual_hbonds <- forward direction") +
  scale_fill_brewer(palette = "Pastel2")

#hbonds vs total score
ggplot(sum) +
  geom_point(aes(x=h_sum_res_summary, y=total_score, color=type)) +   
  geom_text(data = native, aes(x=h_sum_res_summary, y=total_score, label = sequence)) +   
  labs(title ="hbond_vs_total_score", caption = "average total scores across 100 structures generated by FlexPepDock,
    average number of hydrogen_bond between the peptides and the rest of the pose calculated by HbondMetric, 4 native poses are labelled. 
    note that peptides in the reverse direction in 5ni9(DRB1*04:01) have many hydrogen bondings and low total score.") 

#hbonds vs ddg
ggplot(sum) +
  geom_point(aes(x=h_sum_res_summary_mean, y=ddg_mean, color=type_min)) +   
  geom_text(data = native, aes(x=h_sum_res_summary_mean, y=ddg_mean, label = sequence), size = 3) +   
  labs(title ="hbond_vs_ddg") +
  scale_y_continuous(limits = c(-100, 250))

ggplot(rmsd) +
  geom_point(aes(x=sequence, y=total_score, color=type, alpha = 0.8)) +
  geom_text(data = native, aes(x=sequence, y=total_score, label = total_score), size = 3) +   
  theme(axis.text.x=element_text (angle =45, hjust =1, size = 7), legend.position = 'top') +
  scale_x_discrete(labels = abbreviate) +
  labs(title ="sequence_vs_total_score", caption = "filter by rmsd < 0.5 to the lowest energy pose")
  
ggplot(rmsd) +
  geom_point(aes(x=sequence, y=h_sum_res_summary, color=type, alpha = 0.5)) +
  geom_text(data = native, aes(x=sequence, y=h_sum_res_summary, label = h_sum_res_summary), size = 3) +   
  theme(axis.text.x=element_text (angle =45, hjust =1, size = 7), legend.position = 'top') +
  scale_x_discrete(labels = abbreviate) +
  labs(title ="sequence_vs_h_bond", caption = "filter by rmsd < 0.5 to the lowest energy pose")

ggplot(rmsd) + 
  geom_point(aes(x=sequence, y=ddg), color='red', alpha=0.7) + 
  geom_point(aes(x=sequence, y= total_score + 500), color='blue', alpha=0.7) +
  theme(axis.text.x=element_text (angle =45, hjust =1, size = 6)) +
  labs(title ="ddg/total_score_vs_sequence", caption = "red=ddg, blue=total_score, black=#hydrogen_bond on peptides; filter by rmsd < 0.5 to the lowest energy pose") + 
  scale_y_continuous(limits = c(-100, 250), sec.axis = sec_axis(~ . - 500, name = "score")) +
  scale_x_discrete(labels = abbreviate)

c(hbonds_180,hbonds_181,hbonds_182,hbonds_183,hbonds_184,hbonds_185,hbonds_186,hbonds_187,hbonds_188,hbonds_189,hbonds_190,hbonds_191,hbonds_192,hbonds_193,hbonds_194)

data_4x5w %>%
  filter(rmsdvs_lowest < 0.6) %>%
  ggplot() +
  geom_point(aes(x=sequence, y=ddg), color='red', alpha=0.7) + 
  geom_point(aes(x=sequence, y=h_sum_res_summary*10), color='black', alpha=0.7) +
  theme(axis.text.x=element_text (angle =45, hjust =1)) +
  labs(title ="5ni9: ddg/peptide h bonds", caption = "red=ddg, blue=total_score, black=#hydrogen_bond on peptides; filter by rmsd < 0.5 to the lowest energy pose") + 
  scale_y_continuous(limits = c(-100, 250), sec.axis = sec_axis(~ . /10, name = "h bonds")) 

#geom_col(aes(x=sequence, y=h_sum_res_summary/n), alpha=0.7) 
ggplot(data_5ni9) + 
  #geom_point(aes(x=sequence, y=ddg), color='red', shape=1) +
  #geom_point(aes(x=sequence, y=total_score+500), color='blue', shape=18) +
  geom_bar(aes(x=sequence, y=..count..)) +
  theme(axis.text.x=element_text (angle =45, hjust =1)) +
  labs(title ="4x5w: ddg/total_score_vs_sequence", subtitle = "filter by rmsd < 0.5 to the lowest energy pose") + 
  scale_y_continuous(limits = c(-100, 250), sec.axis = sec_axis(~ . - 500, name = "score")) 
#DNEAY_4x5w

ggplot(min_5ni9) + 
  geom_point(aes(x=sequence, y=ddg), color='red', alpha=0.7) + 
  geom_point(aes(x=sequence, y=h_sum_res_summary*10), color='black', alpha=0.7) +  
  geom_point(aes(x=sequence, y=n), color='green') +
  scale_y_continuous(limits = c(-100, 250), sec.axis = sec_axis(~ . /10, name = "h bonds")) +
  labs(title ="5ni9: min energy structure", caption = "red=ddg, green=#poses with rmsd < 0.5, black=#hydrogen_bond on peptides") +
  theme(axis.text.x=element_text (angle =45, hjust =1))

ggplot(min_5ni9) + 
  geom_point(aes(x=sequence, y=ddg), color='red', alpha=0.7) + 
  geom_point(aes(x=sequence, y=h_sum_res_summary*10), color='black', alpha=0.7) +  
  geom_point(aes(x=sequence, y=n), color='green') +
  scale_y_continuous(limits = c(-100, 250), sec.axis = sec_axis(~ . /10, name = "h bonds")) +
  labs(title ="5ni9: min energy structure", caption = "red=ddg, green=#poses with rmsd < 0.5, black=#hydrogen_bond on peptides") +
  theme(axis.text.x=element_text (angle =45, hjust =1))

ggplot(data_4x5w_rmsd) + 
  geom_point(aes(x=sequence, y=total_score)) +
  theme(axis.text.x=element_text (angle =45, hjust =1)) +
  labs(title ="4x5w: ddg/total_score_vs_sequence", subtitle = "filter by rmsd < 0.5 to the lowest energy pose")
#DNEAY_4x5w

ggplot(data_5ni9_rmsd) + 
  geom_point(aes(x=sequence, y=ddg)) +
  theme(axis.text.x=element_text (angle =45, hjust =1)) +
  labs(title ="5ni9: ddg_vs_sequence", subtitle = "filter by rmsd < 0.5 to the lowest energy pose")

ggplot(data_4x5w_rmsd) + 
  geom_point(aes(x=sequence, y=total_score)) +
  theme(axis.text.x=element_text (angle =45, hjust =1)) +
  labs(title ="4x5w: ddg_vs_sequence", subtitle = "filter by rmsd < 0.5 to the lowest energy pose")

ggplot(data_5ni9_rmsd) + 
  geom_point(aes(x=sequence, y=total_score)) +
  theme(axis.text.x=element_text (angle =45, hjust =1)) +
  labs(title ="5ni9: ddg_vs_sequence", subtitle = "filter by rmsd < 0.5 to the lowest energy pose")

ggplot(data_5ni9_rmsd) + 
  geom_point(aes(x=h_sum_res_summary, y=ddg)) +
  labs(x="peptide h-bonds", title ="5ni9: h-bonds_vs_ddg", subtitle = "filter by rmsd < 0.5 to the lowest energy pose")

ggplot(data_5ni9_rmsd) + 
  geom_point(aes(x=total_score, y=ddg)) +
  labs(title ="5ni9: total_score_vs_ddg", subtitle = "filter by rmsd < 0.5 to the lowest energy pose")

ggplot(data_5ni9_rmsd) + 
  geom_point(aes(x=total_score, y=interaction_energy)) +
  labs(title ="5ni9: total_score_vs_interaction_energy", subtitle = "filter by rmsd < 0.5 to the lowest energy pose")

#average per type
#lowest per type

#lowest energy pose per type